//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.ReservationServices = new HashSet<ReservationServices>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> Date_check_in { get; set; }
        public Nullable<System.DateTime> Date_eviction { get; set; }
        public Nullable<int> KolvoDay { get; set; }
        public Nullable<int> NomerID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> PersonnelID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Nomer Nomer { get; set; }
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationServices> ReservationServices { get; set; }
    }
}
